package model.client;

import model.common.CompanyAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 16 14:41:57 EST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyAMClient extends ApplicationModuleImpl implements CompanyAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyAMClient() {
    }

    public void validate() {
        Object _ret = this.riInvokeExportedMethod(this,"validate",null,null);
        return;
    }
}
