package model;

import model.common.CompanyAM;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 16 13:02:12 EST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyAMImpl extends ApplicationModuleImpl implements CompanyAM {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyAMImpl() {
    }

    /**
     * Container's getter for DepartmentsVO.
     * @return DepartmentsVO
     */
    public ViewObjectImpl getDepartmentsVO() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO");
    }
    
    public void validate() {
        
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public ViewObjectImpl getEmployeesVO1() {
        return (ViewObjectImpl)findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for EmployeesVO2.
     * @return EmployeesVO2
     */
    public ViewObjectImpl getEmployeesVO2() {
        return (ViewObjectImpl)findViewObject("EmployeesVO2");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl)findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for EmployeesVO3.
     * @return EmployeesVO3
     */
    public ViewObjectImpl getEmployeesVO3() {
        return (ViewObjectImpl)findViewObject("EmployeesVO3");
    }

    /**
     * Container's getter for DepartmentsVOToEmployeesVO.
     * @return DepartmentsVOToEmployeesVO
     */
    public ViewLinkImpl getDepartmentsVOToEmployeesVO() {
        return (ViewLinkImpl)findViewLink("DepartmentsVOToEmployeesVO");
    }
}
