package model.common.serviceinterface;

import javax.jws.WebMethod;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 16 14:43:24 EST 2013
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/model/common/", name="CompanyAMService",
    wsdlLocation="model/common/serviceinterface/CompanyAMService.wsdl")
@SDODatabinding(schemaLocation="model/common/serviceinterface/CompanyAMService.xsd")
public interface CompanyAMService {
    public static final String NAME = "{/model/common/}CompanyAMService";

    /**
     * Exported method validate from CompanyAM.
     */
    @WebMethod(action="/model/common/validate", operationName="validate")
    @RequestWrapper(targetNamespace="/model/common/types/", localName="validate")
    @ResponseWrapper(targetNamespace="/model/common/types/", localName="validateResponse")
    void validate() throws ServiceException;
}
