package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 16 14:41:57 EST 2013
// ---------------------------------------------------------------------
public interface CompanyAM extends ApplicationModule {
    void validate();
}
